Improved params validation and main function.
darkoperator/dnsrecon pull request #180
Opened 2021-03-19 13:23 UTC by filippolauria

Added a lot of comments to it because it is a big improvement.

Fixed some errors in yandex scraper and get_soa function.
Rewritten se_result_process and also a test for it.

2021-03-21 13:56 UTC, L1ghtn1ng commented on dnsrecon.py
>      for sd in found_hosts:
please change this to something that is more meaning full

2021-03-21 13:57 UTC, L1ghtn1ng commented on dnsrecon.py
> +        for type_, name_, address_or_target_ in res.get_ip(sd):
please see sd comment above

2021-03-21 15:36 UTC, L1ghtn1ng commented on dnsrecon.py
> +        m = re.match(r'^([a-z]+,?)+$', type)
change m to be regex_match

2021-03-21 15:37 UTC, L1ghtn1ng commented on dnsrecon.py
> +        if not m:
see above comment

2021-03-21 15:37 UTC, L1ghtn1ng commented on dnsrecon.py
> +        incorrect_types = [t for t in type.split(',') if t not in valid_types]
change the t variable to something descriptive

2021-03-21 15:38 UTC, L1ghtn1ng commented on dnsrecon.py
> +            print_error("This type of scan is not in the list: {0}".format(','.join(incorrect_types)))
Is this possible to have it as an f-string?

2021-03-21 15:40 UTC, L1ghtn1ng commented on dnsrecon.py
> +            d = arguments.dictionary.strip()
No single char as a vairable

2021-03-21 15:41 UTC, L1ghtn1ng commented on dnsrecon.py
> +                dictionary = d
see comment above

2021-03-21 15:42 UTC, L1ghtn1ng commented on dnsrecon.py
> +                    break
So single char as a variable

2021-03-21 15:42 UTC, L1ghtn1ng commented on dnsrecon.py
> +                # ~ if we cannot find a valid dictionary file,
Can you please remove ~ from all comments and just have a space instead

2021-03-21 15:43 UTC, L1ghtn1ng commented on dnsrecon.py
> +                print_error("Cannot find the dictionary file provided with the tool.")
Please use single quotes ever where it is applicable to use them to keep consistency with the quotes

2021-03-21 15:44 UTC, L1ghtn1ng commented on dnsrecon.py
> +        print_status(f"Using the dictionary file: {dictionary}")
see above comment

2021-03-21 15:44 UTC, L1ghtn1ng commented on dnsrecon.py
> +    for t in types:
no single char vars

2021-03-21 15:45 UTC, L1ghtn1ng commented on dnsrecon.py
> +            print_error(f"{t}: No Domain to target specified!")
see above comment

2021-03-21 15:45 UTC, L1ghtn1ng commented on dnsrecon.py
> +            if t == 'axfr':
see above comment

2021-03-21 15:46 UTC, L1ghtn1ng commented on dnsrecon.py
> +            elif t == 'std':
see above comment about no single chars

2021-03-21 15:46 UTC, L1ghtn1ng commented on dnsrecon.py
> +                    print_error(f"{t}: Invalid Address/CIDR or Address Range provided.")
see above

2021-03-21 15:47 UTC, L1ghtn1ng commented on dnsrecon.py
> +                                                 thread_num=thread_num)
this can be all on 1 line

2021-03-21 15:47 UTC, L1ghtn1ng commented on dnsrecon.py
> +                    continue
no single var chars

2021-03-21 15:48 UTC, L1ghtn1ng commented on dnsrecon.py
> +            elif t == "zonewalk":
see above

2021-03-21 15:48 UTC, L1ghtn1ng commented on dnsrecon.py
> +                print_status(f"{t}: Performing Cache Snooping against NS Server: {ns_server[0]}...")
see above

2021-03-21 15:48 UTC, L1ghtn1ng commented on dnsrecon.py
> +                print_error(f"{t}: This type of scan is not in the list.")
see above

2021-03-21 15:49 UTC, L1ghtn1ng commented on lib/yandexenum.py
> +            return []
is this really needed?

2021-03-21 15:50 UTC, L1ghtn1ng requested changes
please see comments that have been left

2021-03-29 22:48 UTC, L1ghtn1ng commented
Looking good with the new changes, still some changes need doing though

2021-04-04 00:57 UTC, L1ghtn1ng commented
@filippolauria Any update on when you will have finished the changes?

2021-04-04 20:02 UTC, filippolauria commented
Hello, most of the requested changes have been made. Please start merging them. They already solve most of the bugs and issues with the program, other than provide different optimizations ti the code.

2021-04-04 20:27 UTC, merged